#~ ======================================================================
#~ Thomas LEDUC - 26.01.2021
#~ ======================================================================
#~ pip install mkdocs
#~ mkdocs new .
#~ mkdocs serve
#~
#~ pip install mkdocs-bibtex pymdown-extensions
#~ ======================================================================
site_name: The t4gpd user manual
site_author: Thomas LEDUC
site_url: https://t4gpd-docs.readthedocs.io/en/latest

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - python

plugins:
  - search
  #~ - bibtex:
      #~ bib_file: 'docs/refs.bib'
      #~ cite_style: 'pandoc'
      #~ bib_command: '\bibliography'
      #~ full_bib_command: '\full_bibliography'

markdown_extensions:
  - footnotes
  - pymdownx.emoji:

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Introduction': 'introduction.md'
        - 'Reading and writing files': 'io.md'
        - 'Deployment of virtual sensors': 'sensors.md'
        - 'Morphometry': 'morphometry.md'
        - 'Urban layouts analysis': 'layout.md'
        - 'Urban fabrics analysis': 'fabrics.md'
        - 'Urban landscape analysis': 'landscape.md'
        - 'Urban bioclimatic shape analysis': 'bioclimatic.md'
        #~ - 'Bibliography': 'bibliography.md'
    - About:
        - 'About': 'about.md'
        #~ - 'License': 'gpl-3.0.md'
        #~ - 'Release Notes': 'release-notes.md'
